---
- name: install epel repo
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
  when: ansible_distribution == 'CentOS'

- name: install all required packages
  yum:
    name: "{{ netlab_packages }}"
    state: present
  when: inventory_hostname != 'localhost'
  ignore_errors: yes

- name: start required services
  service:
    name: libvirtd
    state: started

- name: setup base directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ netlab_virt_base_path }}"
    - "{{ netlab_virt_vm_path }}"
    - "{{ netlab_virt_images_path }}"
    - "{{ netlab_virt_iso_path }}"

- name: Creates NFS directory
  file: path=/var/nfs state=directory

- name: Create NGINX directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/nginx"
    - "/srv/nginx/images"

- name: NGINX container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
    - "80:80"
    volumes:
    - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "/srv/nginx:/usr/share/nginx/html:ro"

- name: Download Golang 1.10
  get_url:
    url: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
    dest: /root/go.tar.gz
    mode: 0755

- name: Extract tarball
  unarchive:
    src: /root/go.tar.gz
    dest: /root/

- name: Add k8S repository
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
