---
- name: Extract disk from vm
  shell: "virsh domblklist {{item}} --details | grep 'disk' | awk '{print $3}'"
  register: vm_disk

- name: Snapshot vm
  command: "virsh snapshot-create-as --domain {{ item }} {{ item }}  --no-metadata --atomic --disk-only --diskspec {{ vm_disk.stdout }},snapshot=external,file={{ lookup('env', 'SNAPSHOTS_FOLDER') }}/{{ item }}_disk.qcow2"

- name: Add the right permissions
  file:
      mode: 0644
      path: "{{ item }}"
  with_items:
      - "{{ lookup('env', 'SNAPSHOTS_FOLDER') }}/{{ item }}_disk.qcow2"

