---
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: ironic-mysql
spec:
  members: 1
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: "managed-nfs-storage"
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
