apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: default
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      containers:
      - name: mysql-operator-controller
        imagePullPolicy: Always
        image: quay.io/yrobla/mysql-operator
        ports:
        - containerPort: 10254
        args:
          - --v=4
          - --namespace=default
          - --mysql-agent-image=quay.io/yrobla/mysql-agent
