---
- name: Patch restricted security context
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl patch scc restricted -p '{{ item }}'
  with_items:
    - '{"allowHostDirVolumePlugin": true}'
    - '{"allowHostNetwork": true}'
    - '{"allowHostIPC": true}'
    - '{"allowHostPorts": true}'
    - '{"allowPrivilegedContainer": true}'
    - '{"allowedCapabilities": ["DAC_READ_SEARCH", "SYS_RESOURCE", "CAP_NET_RAW", "CAP_NET_ADMIN"]}'
    - '{"requiredDropCapabilities": ["KILL", "MKNOD"]}'
    - '{"runAsUser": {"type": "RunAsAny" }}'
    - '{"seLinuxContext": {"type": "RunAsAny"}}'
    - '{"volumes": ["configMap", "downwardAPI", "emptyDir", "hostPath", "persistentVolumeClaim", "projected", "secret", "nfs"]}'

- name: Label master nodes
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl label nodes testcluster-master-0 {{ item }}
  with_items:
    - "app=nfs-provisioner"
    - "role=master"
    - "ironic-control-plane=enabled"
  ignore_errors: true

- name: Deploy the NFS manifests
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/edge-poc-netlab/third-party/external-storage/nfs-client/deploy/{{ item }}
  with_items:
    - rbac.yaml
    - deployment.yaml
    - class.yaml

- name: Deploy the mysql manifests
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/edge-poc-netlab/third-party/mysql-operator/deploy/{{ item }}
  with_items:
    - rbac.yaml
    - role-binding-template.yaml
    - custom-resource-definitions.yaml
    - role-agent.yaml
    - mysql-deployment.yaml

- name: Deploy the rabbitmq manifests
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/edge-poc-netlab/third-party/rabbitmq/deploy/{{ item }}
  with_items:
    - rabbitmq_rbac.yaml
    - rabbitmq_statefulsets.yaml

- name: Deploy the ironic operator
  git:
      repo: 'https://github.com/redhat-nfvpe/ironic-operator.git'
      dest: "/{{ lookup('env', 'WORKSPACE') }}/ironic-operator"

- name: Install operator files
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/ironic-operator/deploy/{{ item }}
  with_items:
      - crds/ironic_v1alpha1_ironicapi_crd.yaml
      - crds/ironic_v1alpha1_ironicconductor_crd.yaml
      - service_account.yaml
      - role.yaml
      - role_binding.yaml
      - operator.yaml

- name: Apply ironic API CR
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'WORKSPACE') }}/ironic-operator/deploy/crds/ironic_v1alpha1_ironicapi_cr.yaml

- name: Apply ironic conductor CR
  shell: KUBECONFIG={{ lookup('env', 'WORKSPACE') }}/kubeconfig kubectl apply -f {{ lookup('env', 'W      ORKSPACE') }}/ironic-operator/deploy/crds/ironic_v1alpha1_ironicconductor_cr.yaml
