---
- name: Replace secrets in install-config.yml
  hosts: localhost
  become: true

  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    workspace: "{{ lookup('env','WORKSPACE') }}"
    tectonic_secret: "{{ lookup('env','TECTONIC_SECRET') }}"

  tasks:
  - name: Debug secret
    debug:
        msg: "{{ tectonic_secret }}"

  - name: Replace Cluster Secret
    replace:
      path: '{{ workspace }}/ignition_config/install-config.yml'
      regexp: '#SSH_KEYS#'
      replace: '{{ ssh_public_key }}'

  - name: Replace Tectonic Secret
    lineinfile:
      path: '{{ workspace }}/ignition_config/install-config.yml'
      regexp: '#PULL_SECRET#'
      replace: '{{ tectonic_secret | to_json }}}}'
