---
- name: Replace secrets in install-config.yml
  hosts: localhost
  become: true

  vars:
    ssh_private_key: "{{ lookup('file', '~/.ssh/id_rsa') }}"
    workspace: "{{ lookup('env','WORKSPACE') }}"
    tectonic_secret: "{{ lookup('env','TECTONIC_SECRET') }}"

  tasks:
  - name: Replace Cluster Secret
    replace:
      path: '{{ workspace }}/ignition_config/install-config.yml'
      regexp: '#SSH_KEYS#'
      replace: '{{ ssh_private_key }}'

  - name: Replace Tectonic Secret
    replace:
      path: '{{ workspace }}/ignition_config/install-config.yml'
      regexp: '#PULL_SECRET#'
      replace: '{{ tectonic_secret }}'
